### ISSUE TITLE
Reduce the map size back to 1000x1000

### ISSUE THREAD

**Issue by DefaultO** [Geosearchef/placebot#1]
I know. The canvas has been doubled. But the actual image you get from the API request is only 1000x1000px big which causes an index exception.

Fix: Change line 8 in board.py back to BOARD_SIZE_X = 1000

**Comment by Geosearchef** [comment]
This should be fixed in https://github.com/Geosearchef/placebot/commit/bea15a455b37f6fb55d9f406a4eecbc96afa7767#diff-f48dd9d987679212855a89d8af1ebccc19a7808a07c66ea4f1d6682f503dd882R229.

The newest version can deal with both canvases just fine and also only pulls the required canvases (needs to be specified in the target_configuration on the server as generated by the converter)
