### ISSUE TITLE
help me out i dont' fully understand

### ISSUE THREAD

**Issue by gmorningman** [Geosearchef/placebot#2]
how do i use it? this is what i know so far.

install
```shell
git clone https://github.com/Geosearchef/placebot
cd placebot
pip install -r requirements.txt --user
```

Then edit / add lines here for users (in the config_template.json file)
```
{"username": "Hello", "password":  "World"},
{"username": "Hello2", "password":  "World"}
```

I see this (in config_template.json) but I don't understand what to put in this .cfg file?
```
"target_configuration_url": "https://example.com/place.cfg"
```

to start
```shell
python3 ./src/placebot.py
```

**Comment by Geosearchef** [comment]
The bot is built for being used by multiple people / devices for coordination. That's why it pulls its configuration for drawing from a central server. You generate your configuration using the https://github.com/Geosearchef/placebot/blob/main/src/converter/image_converter.py converter. You then put that file on a webserver (or a gist on github) and point all your bots at it.

That way, when the template is changed, bots from different people with different templates won't be fighting each other.

If you give me 5 min though, I'll implement reading a simple file from disk.

**Comment by gmorningman** [comment]
ah thanks

**Comment by Geosearchef** [comment]
You can now specify a local file in `target_configuration_url` and it will load that instead of using http.
